name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build:frontend

    - name: Run tests
      run: pnpm run test:frontend

    - name: Deploy to Vercel
      if: github.ref == 'refs/heads/main'
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: |
        npx vercel --token ${VERCEL_TOKEN} --prod

